.TH MYCOMMAND 1 "Date" "Version" "Manual Title"
.SH NAME
mycommand \- short description of the command
.SH SYNOPSIS
\fBmycommand\fR [\fIoptions\fR] [\fIarguments\fR]
.SH DESCRIPTION
Detailed explanation of what the command does, its options, and arguments.
.SH EXAMPLES
Examples of how to use the command.
.SH SEE ALSO
Related commands or documentation.