#!/bin/bash

options=$(getopt -o a:bc --long alpha:,beta,gamma -- "$@")

eval set -- "$options"

while true; do
    case "$1" in
    -a | --alpha)
        echo "Option a: $2"
        shift 2
        ;;
    -b | --beta)
        echo "Option b"
        shift
        ;;
    -c | --gamma)
        echo "Option c"
        shift
        ;;
    --)
        shift
        break
        ;;
    *)
        echo "Invalid option"
        exit 1
        ;;
    esac
done

echo "Remaining arguments: $@"
echo "Number of remaining arguments: $#"
